name: Build and test run for the package
run-name: build_test

on:
  pull_request:
  workflow_dispatch:

jobs:
    includes_only:
        runs-on: ${{ matrix.ubuntu }}
        strategy:
            matrix:
                include:
                    - ubuntu: "jammy"
                      target_ros2_distro: "humble"
                    - ubuntu: "noble"
                      target_ros2_distro: "jazzy"
                    - ubuntu: "noble"
                      target_ros2_distro: "rolling"
        steps:
            - uses: ros-tooling/setup-ros@v0.7
            - uses: ros-tooling/action-ros-ci@v0.3
              with:
                  package-name: soar_ros
                  target-ros2-distro: ${{ matrix.target_ros2_distro }}
