name: Build and test run for the package
run-name: build_test

on:
    pull_request:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * 0" # every Sunday at midnight UTC

jobs:
    matrix:
        runs-on: ${{ matrix.os}}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: "ubuntu-24.04"
                      target_ros2_distro: "jazzy"
                    - os: "ubuntu-24.04"
                      target_ros2_distro: "kilted"
                    - os: "ubuntu-24.04"
                      target_ros2_distro: "rolling"
        steps:
            - uses: ros-tooling/setup-ros@v0.7
            - uses: ros-tooling/action-ros-ci@v0.4
              with:
                  package-name: soar_ros
                  target-ros2-distro: ${{ matrix.target_ros2_distro }}
