name: Build and test run for the package
run-name: build_test

on:
  pull_request:
  workflow_dispatch:

jobs:
  humble:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
      - uses: ros-tooling/setup-ros@v0.7
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: soar_ros
          import-token: ${{ secrets.GITHUB_TOKEN }}
          target-ros2-distro: humble
