name: package

on:
  workflow_run:
    workflows:
      - build_run
    types:
      - completed
    branches: [main]

  workflow_dispatch:

jobs:
  build_testing:
    runs-on: ubuntu-22.04
    steps:
      - uses: jspricke/ros-deb-builder-action@main
        with:
          ROS_DISTRO: humble
          DEB_DISTRO: jammy
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
